### PR TITLE
Hide modeling

### LINKED ISSUE #225: Hide reference to Modeling chapter for initial release
* Hide last sentence of Monitoring chapter
* Hide and make inactive links to Modeling chapter

### LINKED ISSUE #251: FIX NAV STYLING before pushing to prod
* Gets messed up when you run lint (adds extra spaces)
* `Nav_title.vue` needs to look exactly like this (with no new lines for `</router-link>`):
```
<template>
  <nav id="nav">
    <div>
      <div class="overall-title">
        <div class="text-content">
          <h1 class="nav-title">
            How we<router-link
              to="/monitoring"
              @click.native="scrollToTop"
            >Monitor</router-link><span class="dim_text">|</span><router-link
              to="/modeling"
              @click.native="scrollToTop"
            >Model</router-link><br>Stream Temperature in the<br>
            Delaware River Basin
          </h1>
          <br>
        </div>
      </div>
    </div>
  </nav>
</template>
```

And `Nav.vue` needs to look like this:
```
<template>
  <nav id="nav">
    <div>
      <p>
        <router-link
          to="/monitoring"
          @click.native="scrollToTop"
        >Monitor</router-link><router-link
          to="/modeling"
          @click.native="scrollToTop"
        >Model</router-link>
      </p>
    </div>
  </nav>
</template>
```

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
* Hides modeling chapter from navigation and routing
* Edits final text in monitoring chapter
* Fixes map tooltip placement
* Fixes typo in stroke width for lines on temp chart

Closes #251 
Closes #225 

Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [ ] Safari
- [x] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Review by cnell-usgs — COMMENTED** [review]
Is it easy enough to hash out the links for monitoring too? In the title at the top, could just inactive the link, and then maybe knock out this too: 
image

**Comment by cnell-usgs** [comment]
Also, there's not much hierarchy between the main title and the subtitles in terms of size. Maybe boost the main title a bit? Should we use the same font? Does the title font appear anywhere else?

**Comment by hcorson-dosch-usgs** [comment]
We don't - but the title doesn't look great in the main font used in the viz:
image

**Comment by cnell-usgs** [comment]
alright cool, your call!

**Pull request merged**
