### PR TITLE
initial code to produce svg temperature trends

### PR DESCRIPTION
**Pull request by cnell-usgs**
I'm adding  a subdirectory to svgify the temperature variability line chart. This produces a 600 x 600 svg (within axes dimensions) with a line for all reaches with more than 50 observations. The output svg has `seg_####` as the class for each line with `seg_id_nat`

Adding  @lindsayplatt  for review in case you have any pointers here, working off of code you have developed. I think you also created the original graphic that's currently on the monitoring page and am wondering what, if any, filtering choices were made to the data. This chart generated has a few partially observed lines that aren't in that one, and we are re-evaluating what reaches to include for the new interaction.

### CODE REVIEW

**Comment by lindsayplatt** [comment]
I think the only filtering I did was here https://github.com/usgs-makerspace/temperature-prediction/blob/master/svgify-matrix/prebuild_c2p2_matrix.R#L21-L22, where we removed segments with 0 observations.

**Review by lindsayplatt — APPROVED** [review]

**Comment by hcorson-dosch-usgs** [comment]
@lindsayplatt - I think Colleen was referring to any filtering you might have done when making the 2019 timeseries chart, not the c2p2 or c2p3 matrix --- this one:
image

**Comment by lindsayplatt** [comment]
Oh ... did I make that?! OMG ... code should be in this repo. Searching

**Comment by hcorson-dosch-usgs** [comment]
Lindsay's code [in this PR](https://github.com/usgs-makerspace/temperature-prediction/pull/228). @collnell looks like @lindsayplatt filtered to >180 obs in 2019, but I'm fine w/ your 50 obs threshold if that's what you thought looked good. And we can always tweak later.

**Comment by cnell-usgs** [comment]
OK. Do you want me to add the rects over? What do you need to try the interaction? Or is it off?

**Comment by hcorson-dosch-usgs** [comment]
I think I can use the rectangles that I have already - I'll just adjust them so that they draw to fit this diagram instead of the matrix.

I don't think this is off, it's just sort of on pause while we address the known required changes that we have documented in our issues board.

I may do some exploration of the interaction on my own, outside of work, but we don't want to put any more team hours towards it for now.

**Comment by cnell-usgs** [comment]
IMO we can make it happen. I understand why others have reservations about it, but maybe we can sneak it in there without slowing anything else down 😉

**Review by hcorson-dosch-usgs — APPROVED** [review]

**Pull request merged**
