### PR TITLE
Ch2 loading test

### LINKED ISSUE #78: Explore staggered promise loading for Ch. 2
* Try modifying promise loading so that some data files are not loading until the initial scripts are completed

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
* Staggered data promising and callback functions so that data is loaded in 3 chunks and scripts for each panel are kicked off before data for the next panel is loaded

Fixes #78 

@lindsayplatt - would you mind reviewing this to see if you think this helps ch. 2 to load faster? I think it's an improvement, but would appreciate your take. If you think it is helpful, then I'll merge this into the upstream master branch.

Before making a pull request
----------------------------
First . . .
- [x] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
If no ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@hcorson-dosch I just took a quick glance and it sure seems like this should improve since you have broken apart the data loading into chunks. Hopefully, that means that each of those parts are able to render before the next load is run. Honestly though, I would need to use the waterfall view in the performance test of Chrome developer tools to say for sure. Have to wait for Yeti before I spin this up on a local host to test though (can't pull from GitHub on when on VPN). 

If you don't want to wait, you could open developer tools and run this water fall test in the browser using the performance tab. Compare the results to the long callback call here: https://github.com/usgs-makerspace/temperature-prediction/issues/37#issuecomment-722501624

**Comment by lindsayplatt** [comment]
Just tested on a video call with screenshare and HUZZAH! Asynced loading has allowed the first map to load and be seen without waiting for the others :)

**Comment by hcorson-dosch-usgs** [comment]
* See 3 different callback functions here - one for each 'panel' of chapter 2
image

**Review by lindsayplatt — APPROVED** [review]
Reviewed on the call together.

**Pull request merged**
