### PR TITLE
Refining beeswarm & update hex map

### PR DESCRIPTION
**Pull request by cnell-usgs**
this:
- trades out vizlab logo with basic USGS one - this was feedback we received in snow-to-flow and have no option on
- removes the mid line from the beeswwarm, closing https://github.com/usgs-makerspace/temperature-prediction/issues/229
- cleans up transition functions applied to annotations and axes by recycling functions
- extends y axis of beeswarm (was shorter than plot)
- adds updated version of the hex map based on current data closing https://github.com/usgs-makerspace/temperature-prediction/issues/240
- cleans up hex map code

updated:
image

### CODE REVIEW

**Comment by hcorson-dosch-usgs** [comment]
All these updates look great. Only two things:
1) Looks like there are two zero hexes in the legend?
image

2) Looks like there are now some conflicts in `Modeling.vue` 🙁

**Comment by cnell-usgs** [comment]
the added commits put the conclusion text at the end (https://github.com/usgs-makerspace/temperature-prediction/issues/188) but I'm having some issue with overlapping elements:
scrollsmash

**Comment by hcorson-dosch-usgs** [comment]
Looking so good!! Do you want to let it sit for a bit and look at it again tomorrow? Or should I take a look?

**Comment by hcorson-dosch-usgs** [comment]
Does it have to do w/ the step trigger being in the middle of the page?

**Comment by cnell-usgs** [comment]
I'm not sure. It seems to get sticky halfway through, when the text hits the bottom of the flubber grid. I'm trying now to set it so that the charts become unsticky after the last text step, that may be all that is needed

**Comment by cnell-usgs** [comment]
OK - I've got the text in there and removed some text steps that were repetitive to the ending text. The text is no longer overlapping because I'm using and `ifelse` to make it hidden/visible on the last step. 

This works great EXCEPT there is a weird large space after the last step that I cannot figure out how to get rid of. I added the class `#end` to the last step and used `height=auto` to elimate extra spacing on the step. Still there! And this might be problematic because flubber uses the step id?

In my inspector this space belongs to  nothing - it's within `<div id="modeling">` but has no element associated with it which is weird. I suspect this means it's being caused by the height setting on the modeling div?

**Review by hcorson-dosch-usgs — APPROVED** [review]
Looks SO good. Thanks for tackling all of these edits, Colleen!

**Pull request merged**
